function def = allowed_param_list()

def.CONTROL = {
  'isgw', ...
  'isbse', ...
  'enable_k_points', ...
  'output_dir', ...
  'prefix', ...
  'groundstate_dir', ...
  'groundstate_type', ...
  'storage_dir', ...
  'outfile', ...
  'log_level', ...
  'log_file' ...
};

def.SYSTEM = {
  'number_bands_in_summation', ...
  'energy_band_index_min',  ...
  'energy_band_index_max' ...
};

def.CUTOFFS = {
  'coulomb_truncation_method', ...
  'coulomb_truncation_parameter', ...
  'coulomb_cutoff', ...
  'density_cutoff' ...
};

def.FREQUENCY = {
  'frequency_dependence', ...
  'frequency_dependence_method', ...
  'frequency_low_cutoff', ...
  'delta_frequency', ...
  'number_imaginary_freqs', ...
  'eta', ...
  'cd_integration_method', ...
  'cd_integration_parameter', ...
  'cd_residual_method' ...
};

def.ISDF = {
  'isisdf', ...
  'compute_vc', ...
  'compute_vn', ...
  'compute_nn', ...
  'isdf_ratio', ...
  'isdf_ratio_type1', ...
  'isdf_ratio_type2', ...
  'isdf_ratio_type3', ...
  'adaptive_threshold_type1', ...
  'adaptive_threshold_type2', ...
  'adaptive_threshold_type3', ...
  'adaptive_num_add_type1', ...
  'adaptive_num_add_type2', ...
  'adaptive_num_add_type3', ...
  'adaptive_candidate_ratio_type1', ...
  'adaptive_candidate_ratio_type2', ...
  'adaptive_candidate_ratio_type3', ...
  'adaptive_max_add_frac_type1', ...
  'adaptive_max_add_frac_type2', ...
  'adaptive_max_add_frac_type3', ...
  'adaptive_max_cond_type1', ...
  'adaptive_max_cond_type2', ...
  'adaptive_max_cond_type3', ...
  'adaptive_use_cond_guard', ...
  'adaptive_batch_size', ...
  'adaptive_weight_batch_size', ...
  'exxmethod_type1', ...
  'exxmethod_type2', ...
  'exxmethod_type3', ...
  'exxmethod', ...
  'seed', ...
  'init', ...
  'weight', ...
  'sys', ...
  'is_helper', ...
  'validate_hf', ...
  'inv_strategy', ...
  'inv_param', ...
  'inv_ratio', ...
  'auto_inv_param', ...
  'order', ...
  'chol_maxit' ...
};

def.COHSEX = {
  'exact_ch', ...
  'ex_use_which_isdf' ...
};

def.SUPERCELL = {
  'is_supercell', ...
  'use_sc_isdf', ...
  'sc_adaptive', ...
  'k1', ...
  'k2', ...
  'k3', ...
  'isdf_source_dir' ...
};

def.FORMAL = {
  'wf_seed', ...
  'eo_e0', ...
  'eo_delta', ...
  'run_qp_cohsex', ...
  'enable_profile' ...
};

end
