function def = allowed_param_list()

def.CONTROL = {
    'isgw', ...
    'isbse', ...
    'output_dir', ...
    'prefix', ...
    'groundstate_dir', ...
    'groundstate_type', ...
    'storage_dir', ...
    'outfile' ...
};

def.SYSTEM = {
    'number_bands_in_summation' ...
};

def.CUTOFFS = {
    'coulomb_truncation_method', ...
    'coulomb_cutoff', ...
    'wavefunc_cutoff', ...
    'density_cutoff' ...
};

def.FREQUENCY = {
    'frequency_dependence', ...
    'frequency_dependence_method', ...
    'frequency_low_cutoff', ...
    'delta_frequency', ...
    'number_imaginary_freqs', ...
    'eta', ...
    'cd_int_method', ...
    'cd_res_method' ...
};

def.ISDF = {
    'isisdf', ...
    'isdf_ratio', ...
    'isdf_ratio_type1', ...
    'isdf_ratio_type2', ...
    'isdf_ratio_type3', ...
    'exxmethod', ...
    'seed', ...
    'init', ...
    'weight', ...
    'sys' ...
};

end
