function def = default_param_values()
% Return default values for all supported blocks

def.CONTROL = struct( ...
    'prefix', 'calc', ...
    'calculation', 'scf', ...
    'verbosity', 'low' ...
);

def.SYSTEM = struct( ...
    'ecutwfc', 40.0, ...
    'ecutrho', 160.0, ...
    'nbnd', 100, ...
    'sigma', 0.1, ...
    'gw_method', 'G0W0' ...
);

def.FREQUENCY = struct( ...
    'n_freq', 100, ...
    'wmin', 0.0, ...
    'wmax', 10.0, ...
    'broadening', 0.05 ...
);

def.ISDF = struct( ...
    'isISDF', true, ...
    'cauchy_threshold', 1e-6 ...
);

def.CUTOFFS = struct( ...
    'ecutcoul', 10.0, ...
    'qcutz', 2.0 ...
);
end
