function def = default_constant()
% default_Constant - Define fixed numerical constants and tolerances

def = struct( ...
    'nv', -1, ...                            
    'nv_ener',  -1, ...
    'nv_oper',  -1, ... 
    'nc', -1, ...                            
    'nc_ener',  -1, ...
    'nc_oper',  -1, ... 
    'n_oper',  -1, ... 
    'n_ener',  -1, ... 
    'ng', -1, ... 
    'nr', -1, ... 
    'ne', -1, ... 
    'vol', -1, ... 
    'bohr_to_angstrom', 0.529177, ...        
    'TOL_ZERO', 1e-12, ...                    
    'TOL_SMALL', 1e-6, ...                    
    'INF', 1e+12, ...                    
    'ry2ev', 13.60569253, ...                    
    'ZERO', 0.0, ...                    
    'CZERO', complex(0.0, 0.0), ...                    
    'limitone', 0.25*1e+6, ...                    
    'limittwo', 0.25, ...                    
    'sexcut', 4.0, ...                    
    'eta', 1e-4 ...                         
);
 
end % EOF