function def = default_GWCal()
def.FREQUENCY = struct( ...
    'fileName', 'GWoutput', ...
    'frequency_dependence', 0, ...
    ... % if FREQUENCY.frequency_dependence == 2
    'frequency_dependence_method', 0, ...
    'frequency_low_cutoff', -1.0, ...
    'delta_frequency', 2, ...
    'number_imaginary_freqs', 15, ...
    'eta', 1e-4, ...
    'cd_integration_method', 0, ...
    'cd_integration_parameter', 2.0, ...
    'cd_residual_method', 0 ... 
);


end % EOF