% License-Identifier: BSD-3-Clause
%
% Copyright (C) 2026
%
% Authors (see AUTHORS file for details): ZZ
%
% Last modified: 2026/05/20 ZZ

function def = default_param_values()
% Return default values for all supported blocks

def.CONTROL = struct( ...
  'isgw', 1, ...,
  'isbse', 0, ...
  'enable_k_points', 0, ...
  'output_dir', './', ...
  'prefix', 'QP', ...
  'groundstate_dir', [], ...
  'groundstate_type', 'qe', ...
  'storage_dir', './SAVE/', ...
  'outfile', 'GWoutput', ...
  'log_level', 1, ...
  'log_file', []...
);

% System information, parameters about cutoff
def.SYSTEM = struct( ...
  'number_bands_in_summation', -1, ...
  'energy_band_index_min', -1, ...
  'energy_band_index_max', -1 ...
);

def.CUTOFFS = struct( ...
  'coulomb_truncation_method', 2, ...
  'coulomb_truncation_parameter', 5.0, ...
  'coulomb_cutoff', -1.0, ...
  'density_cutoff', -1 ...
);

def.FREQUENCY = struct( ...
  'frequency_dependence', 0, ...
  ... % if FREQUENCY.frequency_dependence == 2
  'frequency_dependence_method', 2, ...
  'frequency_low_cutoff', -1.0, ...
  'broadening', 0.25, ...
  'delta_frequency', 0.146997295433511, ...
  'number_imaginary_freqs', 15, ...
  'eta', 1e-4, ...
  'cd_integration_method', 0, ...
  'cd_integration_parameter', 2.0, ...
  'cd_residual_method', 0 ... 
);

def.ISDF = struct( ...
  'isisdf', 1, ...
  'compute_vc', true, ...
  'compute_vn', true, ...
  'compute_nn', true, ...
  'isdf_ratio_type1', 8.0, ...
  'isdf_ratio_type2', 8.0, ...
  'isdf_ratio_type3', 8.0, ...
  'adaptive_threshold_type1', 2e-4, ...
  'adaptive_threshold_type2', 2e-6, ...
  'adaptive_threshold_type3', 2e-6, ...
  'adaptive_num_add_type1', 16, ...
  'adaptive_num_add_type2', 16, ...
  'adaptive_num_add_type3', 16, ...
  'adaptive_candidate_ratio_type1', 2.0, ...
  'adaptive_candidate_ratio_type2', 2.0, ...
  'adaptive_candidate_ratio_type3', 2.0, ...
  'adaptive_max_add_frac_type1', 1.0, ...
  'adaptive_max_add_frac_type2', 1.0, ...
  'adaptive_max_add_frac_type3', 1.0, ...
  'adaptive_max_cond_type1', 1e12, ...
  'adaptive_max_cond_type2', 1e12, ...
  'adaptive_max_cond_type3', 1e12, ...
  'adaptive_use_cond_guard', true, ...
  'adaptive_batch_size', 64, ...
  'exxmethod_type1', '', ...
  'exxmethod_type2', '', ...
  'exxmethod_type3', '', ...
  'exxmethod', '', ...
  'seed', 0, ...
  'init', 'random', ...
  'weight', 'add', ...
  'sys', [], ... 
  'is_helper', false, ...
  'validate_hf', false, ...
  'inv_strategy', 'dir', ...
  'inv_param', 1e-12, ...
  'inv_ratio', 0.75, ...
  'auto_inv_param', false, ...
  'order', 1, ...
  'debug_checks', false, ...
  'debug_level', 'error', ...
  'debug_tags', [], ...
  'iscauchy', false ...
);

def.COHSEX = struct( ...
  'exact_ch', false, ...
  'ex_use_which_isdf', 'vn' ...
);

def.SUPERCELL = struct( ...
  'is_supercell', false, ...
  'use_sc_isdf', false, ...
  'sc_adaptive', false, ...
  'k1', 1, ...
  'k2', 1, ...
  'k3', 1, ...
  'isdf_source_dir', '' ...
);

def.FORMAL = struct( ...
  'wf_seed', 42, ...
  'eo_e0', -2.0, ...
  'eo_delta', 0.05, ...
  'run_qp', true, ...
  'enable_profile', false ...
);

end
