options_scf = setksopt();
% options_scf = setksopt();
% % options_scf.nc = nc; % get an extra band.
% options_scf.useace = 1;
% % options_scf.what2mix = 'rho';
% % options_scf.mixtype = 'broyden';
% % options_scf.eigmethod = 'eigs';
% options_scf.verbose = 0;
% options_scf.maxphiiter = 30;
% options_scf.phitol = 1e-8;