function def = default_ISDFCauchy()
% Return default configuration for ISDFCauchy block

def = struct( ...
    'isISDF', true, ...
    'vcrank_ratio', -1.0, ...
    'vsrank_ratio', -1.0, ...
    'ssrank_ratio', -1.0, ...
    'exxmethod', 'kmeans', ...
    'seed', 0, ...
    'init', 'wrs', ...
    'weight', 'add', ...
    'sys', [], ...
    ...
    'isCauchy', 0, ...
    'optionsCauchy', [], ...
    'froErr', 1e-6, ...
    'MaxIter', 10 ...
);
end
