function def = default_param_values()
% Return default values for all supported blocks

def.CONTROL = struct( ...
    'isgw', 1, ...,
    'isbse', 0, ...
    'output_dir', './', ...
    'prefix', 'QP', ...
    'groundstate_dir', [], ...
    'groundstate_type', 'kssolv', ...
    'storage_dir', './QP.save/', ...
    'outfile', 'GWoutput' ...
);

% System information, parameters about cutoff
def.SYSTEM = struct( ...
    'number_bands_in_summation', -1, ...
    'energy_band_index_min', -1, ...
    'energy_band_index_max', -1 ...
);

def.CUTOFFS = struct( ...
    'coulomb_truncation_method', 2, ...
    'coulomb_truncation_parameter', 5.0, ...
    'coulomb_cutoff', 5.0, ...
    'density_cutoff', -1 ...
);

def.FREQUENCY = struct( ...
    'frequency_dependence', 0, ...
    ... % if FREQUENCY.frequency_dependence == 2
    'frequency_dependence_method', 0, ...
    'frequency_low_cutoff', -1.0, ...
    'delta_frequency', 2, ...
    'number_imaginary_freqs', 15, ...
    'eta', 1e-4, ...
    'cd_int_method', 0, ...
    'cd_res_method', 0 ... 
);

def.ISDF = struct( ...
    'isisdf', 1, ...
    'isdf_ratio', 8.0, ...
    'isdf_ratio_type1', -1.0, ...
    'isdf_ratio_type2', -1.0, ...
    'isdf_ratio_type3', -1.0, ... 
    'exxmethod', 'kmeans', ...
    'seed', 0, ...
    'init', 'random', ...
    'weight', 'add', ...
    'sys', [] ... 
);

end
